services:

  postgres:
    image: postgres:17
    container_name: rag_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: rag_ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    entrypoint: >
      sh -c "
      ollama serve &
      sleep 10 &&
      ollama pull qwen3:8b &&
      ollama pull nomic-embed-text &&
      wait
      "

  whisper:
    build: ./whisper
    container_name: rag_whisper

    ports:
      - "9000:9000"

  piper:
    build: ./piper

    container_name: rag_piper

    ports:
      - "9100:9100"

volumes:
  postgres_data:
  ollama_data: